config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'groups' => 'groups#index'
  get 'contact' => 'home#contact'
  get 'search' => 'groups#search'
  get 'result' => 'groups#result'
  get 'meetings/update_rooms', as: 'update_rooms'
  get 'meetings/:id/edit_rooms', to:'meetings#update_rooms', as: 'edit_rooms'
  
  resources :groups
  resources :meetings
  
  resources :groups do
      member do
          post :addUser 
          post :removeUser
      end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_and_belongs_to_many :users, -> { uniq }
    has_many :meetings, dependent: :destroy
    
    searchkick
    
    validates :name, presence: true, length: { maximum: 100 }, uniqueness: true
    validates :description, presence:true
    validates :max_members, presence:true, numericality: { only_integer: true }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    layout "groups"
    before_action :authenticate_user!
    before_action :valid_user, only: [:destroy, :edit]
    
    def index
        @groups = current_user.groups.all.paginate(:page => params[:page])
        @usergroups = current_user.groups.all
    end

    def search
        @user = current_user
        @usergroups = current_user.groups.all
        @groups = Group.all.paginate(:page => params[:page])
        @responder = APIResponses::PurdueAPICalls.new.get_details('Courses')
    end
    

    def show
        @group = Group.find(params[:id])
        @usergroups = current_user.groups.all
        @members = @group.users.all
        @meetings = @group.meetings.all
    end
  
    def new
        @group = Group.new
        @usergroups = current_user.groups.all
    end
    
    def edit
        @group = Group.find(params[:id])
        @usergroups = current_user.groups.all
    end

    def update
        @group = Group.find(params[:id])
        @usergroups = current_user.groups.all
        if @group.update_attributes(group_params)
            flash[:success] = "Group updated"
            redirect_to @group
        else
        render 'edit'
        end
    end
  
    def create
        @group = Group.new(group_params)
        @usergroups = current_user.groups.all
        if @group.save
            @group.update_attribute(:user_id,current_user.id)
            @group.users << current_user
            flash[:success] = "Group Created"
            redirect_to groups_url
        else
            render 'new'
        end
    end

    def destroy
        @group = Group.find(params[:id])
        @usergroups = current_user.groups.all
        @group.destroy
        flash[:success] = "Group Deleted"
        redirect_to groups_url
    end
  
    def addUser
        @group = Group.find(params[:group_id])
        @usergroups = current_user.groups.all
        if @group.users.all.count >= @group.max_members
            flash[:notice] = "This group is full."
        else    
            @group.users << current_user
            flash[:success] = "You have joined the group!"
        end
        redirect_to group_url(@group)
    end
    
    def removeUser
        @group = Group.find(params[:group_id])
        @usergroups = current_user.groups.all
        @user = User.find(params[:user_id])
        if @user.id == current_user.id
            if (current_user.admin || current_user.id = @group.user_id && current_user.id != @group.user_id)
                @group.users.delete(@user)
                flash[:success] = "You have left the group"
                redirect_to groups_url
            else
                flash[:notice] = "You cannot do that."
                redirect_to group_url(@group)
            end
        else 
            @group.users.delete(@user)
            flash[:success] = @user.first_name + " has been removed from the group."
            redirect_to group_url(@group)
        end
    end
    
    def result
        @usergroups = current_user.groups.all
        if params[:search] == ""
            @groups = Group.search "*"
        else
            @groups = Group.search params[:search],  page: params[:page], per_page: 5
        end
    end
    
    def valid_user
        @group = Group.find(params[:id])
        @usergroups = current_user.groups.all
        unless current_user.admin || @group.user_id == current_user.id
            flash[:notice] = "You do not have permission to perform that action."
            redirect_to groups_url
        end
    end

    private
    
        def group_params
            params.require(:group).permit(:name, :description, :max_members)
        end
end

app/helpers/groups_helper.rb
module GroupsHelper
    def userInGroup
        @group.users.where(:id => current_user.id).present?
    end
    
    def isOwner?(id)
        @group.user_id == id
    end
end

app/views/groups/_description.html.erb
<br>
<%= @group.description %>

app/views/groups/_group.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <strong id="group-head">
                <%= group.name %>
            </strong>
        </h3>
    </div>
    <div class="panel-body">
        <strong>Details</strong>
        <%= link_to group, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-question-sign"></i>
        <% end %>
        <br>
        <strong>New Meeting</strong>
        <%= link_to new_meeting_path(:group_id => group.id), class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-plus"></i>
        <% end %>
        <br>
        <% if group.user_id == current_user.id || current_user.admin %>
            <strong>Edit Group</strong>
            <%= link_to edit_group_path(group), class: "btn btn-default" do %>
                <i class="glyphicon glyphicon-pencil"></i>
            <% end %> 
        <% end %>
    </div>
</div>

app/views/groups/_meetings.html.erb
<%= link_to new_meeting_path(:group_id => @group.id), class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-plus"> New Meeting</i>
<% end %>

<% if @meetings %>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Purpose</th>
                <th>Building</th>
                <th>Room</th>
                <th>Time</th>
                <% if @group.user_id == current_user.id || current_user.admin %>
                    <th>Actions</th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @meetings.each do |meeting| %>
                <tr>
                    <td><%= meeting.purpose %></td>
                    <td><%= meeting.building %></td>
                    <td><%= meeting.room %></td>
                    <td><%= meeting.time.strftime("%m/%d/%y: %I:%M %p") %></td>
                    <% if @group.user_id == current_user.id || current_user.admin %>
                        <td>
                            <%= link_to edit_meeting_url(meeting,:group_id => @group.id, :meeting_id => meeting.id) do %>
                                <i class="glyphicon glyphicon-pencil"></i>
                            <% end %>
                            <%= link_to meeting_url(meeting,:group_id => @group.id, :meeting_id => meeting.id), method: :delete, data: { confirm: "You sure?" } do %>
                                <i class="glyphicon glyphicon-remove"></i>
                            <% end %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/groups/_members.html.erb
<% if @members %>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @members.each do |user| %>
                <tr>
                    <td><%= user.first_name %></td>
                    <td><%= user.last_name %></td>
                    <td><%= user.email %></td>
                    <td>
                        <% if (user.id == @group.user_id) %>
                            Creator
                        <% else %>
                            Member
                        <% end %>
                    </td>
                    <td>
                        <% if @group.user_id == current_user.id || current_user.admin %>
                            <%= link_to removeUser_group_path(@group, :group_id => @group.id, :user_id => user.id), method: :post do %>
                        <i class="glyphicon glyphicon-remove"></i>
                    <% end %> 
                <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/groups/_nav.html.erb
<ul class="nav nav-tabs">
  <li class="active", id="description-tab"><%= link_to "Description", '#' , 'data-toggle':"tab" %></li>
  <li id="meetings-tab"><%= link_to "Meetings", '#' , 'data-toggle':"tab" %></li>
  <li id="members-tab"><%= link_to "Members", '#' , 'data-toggle':"tab" %></li>
</ul>

<br>

<div id="group-description">
  <%= render "description" %>
</div>

<div class="collapsable-section", id="meetings">
  <%= render "meetings" %>
</div>

<div class="collapsable-section", id="members">
  <%= render "members" %>
</div>

app/views/groups/edit.html.erb
<%= form_for(@group) do |f| %>
    <%= render 'shared/error_messages', form_object: @group %>
    <div class = "col-xs-6">
    <div class = "row">
    <%= f.label :name, "Edit Group Name"%>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :description, "Edit Group Description" %>
    <%= f.text_area :description, class: 'form-control' %>
    
    <%= f.label :max_members, "Edit Maximum Group Size" %>
    <%= f.number_field :max_members, class: 'form-control' %>
    <br>
    </div>
    <div class = "row">
    <%= f.submit "Submit Changes", class: "btn btn-primary" %>
    </div>
    </div>
<% end %>

app/views/groups/index.html.erb
<h2>My Groups</h2>

<% if @groups.count == 0 %>
    Oops! Looks like you haven't joined any groups!
<% end %>

<%= render @groups %>
<% will_paginate @groups %>

app/views/groups/new.html.erb
<%= form_for(@group) do |f| %>
    <%= render 'shared/error_messages', form_object: @group %>
    <div class = "col-xs-6">
    <div class = "row">
    <%= f.label :name, "Group Name"%>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :description, "Group Description" %>
    <%= f.text_area :description, class: 'form-control' %>
    
    <%= f.label :max_members, "Maximum Group Size" %>
    <%= f.number_field :max_members, class: 'form-control' %>
    <br>
    </div>
    <div class = "row">
    <%= f.submit "Create Group", class: "btn btn-primary" %>
    </div>
    </div>
<% end %>

app/views/groups/result.html.erb
<h2>Search Results</h2>
<%= form_tag(result_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Groups" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<br>

<% if !@groups %>
    Your search returned no results.  
<% end %>

<%= render @groups %>
<% will_paginate @groups %>

app/views/groups/search.html.erb
<%= form_tag(result_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Groups" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<br>

<%= render @groups %>
<% will_paginate @groups %>


    

app/views/groups/show.html.erb
<div class="page-header">
  <h1><%= @group.name %>
    <% if !userInGroup %>
        <%= button_to "Join Group", addUser_group_path(@group, :group_id => @group.id), :class => "btn btn-success" %>
    <% else %>
        <%= button_to "Leave Group", removeUser_group_path(@group, :group_id => @group.id, :user_id => current_user.id), :class => "btn btn-danger" %>
    <% end %>
    <% if @group.user_id == current_user.id || current_user.admin %>
      <%= link_to @group, method: :delete, class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-remove">Delete</i>
      <% end %>
    <% end %>
  </h1>
</div>
 
<%= render 'nav' %>