config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'groups' => 'groups#index'
  get 'contact' => 'home#contact'
  get 'search' => 'groups#search'
  get 'result' => 'groups#result'
  get 'meetings/update_rooms', as: 'update_rooms'
  get 'meetings/:id/edit_rooms', to:'meetings#update_rooms', as: 'edit_rooms'
  
  resources :groups
  resources :meetings
  
  resources :groups do
      member do
          post :addUser 
          post :removeUser
      end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<a name="about"></a>
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Want to contribute?</h1>
                        <h3>Contact: syellin@purdue.edu</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</a>

app/views/home/index.html.erb
<a name="about"></a>
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>BoilerMeet</h1>
                        <h3>Find Your Study Group</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <% if !current_user %>
                                <li>
                                    <%= link_to "Create Account", new_user_registration_path, :class => "btn btn-default btn-lg" %>
                                </li>
                                <li>
                                    <%= link_to "Sign In", new_user_session_path, :class => "btn btn-default btn-lg"  %>
                                </li>
                                <li>
                                    <%= link_to "Contact", contact_path, :class => "btn btn-default btn-lg"  %>
                                </li>
                            <% else %>
                                <li>
                                    <%= link_to "Find My Group", search_path, :class => "btn btn-default btn-lg"  %>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</a>

<div class="content-section-a">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">So, what is BoilerMeet?</h2>
                <p class="lead">BoilerMeet is a hub for Purdue Students to find classmates to study with.  You can find peers in your classes, make study groups, and plan meetings, all from the BoilerMeet web app!</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <%= image_tag "study_group.jpg", class: "img-responsive" %>
            </div>
        </div>
    </div>
</div>

<div class="content-section-b">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">How was BoilerMeet made?</h2>
                <p class="lead">BoilerMeet was made with the Ruby on Rails framework, and is hosted on Heroku.  All the code is open sourced and available on BitBucket. <br> Special thank you to the team at api.purdue.io</p>
            </div>
            <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                <%= image_tag "ruby-on-rails.jpg", class: "img-responsive" %>
            </div>
        </div>
    </div>
</div>