config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'groups' => 'groups#index'
  get 'contact' => 'home#contact'
  get 'search' => 'groups#search'
  get 'result' => 'groups#result'
  get 'meetings/update_rooms', as: 'update_rooms'
  get 'meetings/:id/edit_rooms', to:'meetings#update_rooms', as: 'edit_rooms'
  
  resources :groups
  resources :meetings
  
  resources :groups do
      member do
          post :addUser 
          post :removeUser
      end
  end
end

app/views/layouts/_flashes.html.erb
<div class="row" align = center>
    <div class="col-md-6 col-md-offset-3">  
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "BoilerMeet", root_url,:class =>"navbar-brand topnav"%>
        </div>
        <% if user_signed_in? %>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li id="link-1">
                        <%= link_to "My Groups", groups_path%>
                    </li>
                    <li class = "head-link">
                        <%= link_to "Edit Profile", edit_user_registration_path %>
                    </li>
                    <li class = "head-link">
                        <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
                    </li>
                </ul>
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_side.html.erb
<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <%= link_to "BoilerMeet", root_path %>
                </li>
                <li>
                    <%= link_to "Find Groups", search_path %>
                </li>
                <li>
                    <%= link_to "Create Group", new_group_path %>
                </li>
                
                <li>
                    <%= link_to "My Groups", groups_path %>
                </li>
                <li>
                    <%= link_to "Edit Account", edit_user_registration_path %>
                </li>
                <li>
                    <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class = "row">
                            <%= render 'layouts/flashes' %>
                            <a id="hamburger" class="Fixed" href="#my-menu"><span></span></a>
                            <%= yield %>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

</body>

app/views/layouts/_slidenav.html.erb
<nav id="my-menu">
    <ul>
        <li class="Divider">Meeting Navigator</li>
        <% if @usergroups %>
            <% @usergroups.each do |group| %>
                <li>
                    <a><%= group.name %></a>
                    <ul>
                        <% group.meetings.each do |meeting| %> 
                            <li>
                                <a><%= meeting.purpose %></a>
                                <ul>
                                    <li class = "Divider">Building</li>
                                    <li><a><%= meeting.building %></a></li>
                                    <li class = "Divider">Room</li>
                                    <li><a><%= meeting.room %></a></li>
                                    <li class = "Divider">Time</li>
                                    <li><a><%= meeting.time.strftime("%m/%d/%y: %I:%M %p") %> </a></li>                                    
                                </ul>
                            </li>
                        <% end %>
                    </ul>
                </li>
            <% end %>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoilerMeet</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= stylesheet_link_tag  'landing-page', media:'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  
  <%= render 'layouts/shim' %>
  <%= render 'layouts/header' %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/layouts/groups.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoilerMeet</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag  'groups', media:'all' %> 
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= render 'layouts/side' %>
</head>
<%= render 'layouts/slidenav' %>
</html>